version: "3.9"

services:
  bytebot-desktop:
    image: ghcr.io/bytebot-ai/bytebot-desktop:edge
    container_name: bytebot-desktop
    restart: unless-stopped
    privileged: true
    hostname: computer
    shm_size: "2g"
    ports:
      - "9990:9990" # noVNC + desktop control
    environment:
      DISPLAY: ":0"
    networks:
      - bytebot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9990"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:16-alpine
    container_name: bytebot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: bytebotdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bytebot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  bytebot-agent:
    image: ghcr.io/bytebot-ai/bytebot-agent:edge
    container_name: bytebot-agent
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/bytebotdb
      BYTEBOT_DESKTOP_BASE_URL: http://bytebot-desktop:9990
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - postgres
      - bytebot-desktop
    networks:
      - bytebot-network
    ports:
      - "9991:9991"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9991/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  bytebot-ui:
    image: ghcr.io/bytebot-ai/bytebot-ui:edge
    container_name: bytebot-ui
    restart: unless-stopped
    environment:
      NODE_ENV: production
      BYTEBOT_AGENT_BASE_URL: http://bytebot-agent:9991
      BYTEBOT_DESKTOP_VNC_URL: http://bytebot-desktop:9990/websockify
    depends_on:
      - bytebot-agent
    networks:
      - bytebot-network
    ports:
      - "9992:9992"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9992"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bytebot-network:
    driver: bridge

volumes:
  postgres_data:
